"""
AI tools, models, and connectors catalog.
Each entry defines how to detect a tool across multiple signal types.
"""

CATALOG = {
    # ── LLM APIs ──────────────────────────────────────────────────────────────
    "openai": {
        "category": "LLM API",
        "label": "OpenAI",
        "packages": ["openai"],
        "imports": ["openai", "from openai"],
        "env_keys": ["OPENAI_API_KEY", "OPENAI_ORG_ID", "OPENAI_BASE_URL"],
        "urls": ["api.openai.com", "openai.azure.com"],
        "config_files": [],
    },
    "anthropic": {
        "category": "LLM API",
        "label": "Anthropic / Claude",
        "packages": ["anthropic", "@anthropic-ai/sdk", "claude"],
        "imports": ["anthropic", "from anthropic", "@anthropic-ai/sdk"],
        "env_keys": ["ANTHROPIC_API_KEY", "CLAUDE_API_KEY"],
        "urls": ["api.anthropic.com"],
        "config_files": ["CLAUDE.md", ".claude/"],
    },
    "google_ai": {
        "category": "LLM API",
        "label": "Google AI / Gemini",
        "packages": ["google-generativeai", "google-cloud-aiplatform", "@google/generative-ai", "vertexai"],
        "imports": ["google.generativeai", "google-generativeai", "vertexai", "@google/generative-ai"],
        "env_keys": ["GOOGLE_API_KEY", "GEMINI_API_KEY", "VERTEX_AI_PROJECT", "GOOGLE_CLOUD_PROJECT"],
        "urls": ["generativelanguage.googleapis.com", "aiplatform.googleapis.com"],
        "config_files": [],
    },
    "azure_openai": {
        "category": "LLM API",
        "label": "Azure OpenAI",
        "packages": ["azure-ai-inference", "@azure/openai"],
        "imports": ["azure.ai.inference", "@azure/openai"],
        "env_keys": ["AZURE_OPENAI_API_KEY", "AZURE_OPENAI_ENDPOINT", "AZURE_OPENAI_DEPLOYMENT"],
        "urls": ["openai.azure.com", "cognitiveservices.azure.com"],
        "config_files": [],
    },
    "aws_bedrock": {
        "category": "LLM API",
        "label": "AWS Bedrock",
        "packages": ["boto3", "botocore"],
        "imports": ["boto3", "bedrock"],
        "env_keys": ["AWS_BEDROCK_REGION", "AWS_ACCESS_KEY_ID"],
        "urls": ["bedrock.amazonaws.com", "bedrock-runtime."],
        "config_files": [],
    },
    "cohere": {
        "category": "LLM API",
        "label": "Cohere",
        "packages": ["cohere", "cohere-python"],
        "imports": ["cohere", "import cohere"],
        "env_keys": ["COHERE_API_KEY"],
        "urls": ["api.cohere.ai", "api.cohere.com"],
        "config_files": [],
    },
    "mistral": {
        "category": "LLM API",
        "label": "Mistral AI",
        "packages": ["mistralai", "@mistralai/mistralai"],
        "imports": ["mistralai", "@mistralai/mistralai"],
        "env_keys": ["MISTRAL_API_KEY"],
        "urls": ["api.mistral.ai"],
        "config_files": [],
    },
    "groq": {
        "category": "LLM API",
        "label": "Groq",
        "packages": ["groq"],
        "imports": ["groq", "from groq"],
        "env_keys": ["GROQ_API_KEY"],
        "urls": ["api.groq.com"],
        "config_files": [],
    },
    "together_ai": {
        "category": "LLM API",
        "label": "Together AI",
        "packages": ["together"],
        "imports": ["together"],
        "env_keys": ["TOGETHER_API_KEY"],
        "urls": ["api.together.xyz"],
        "config_files": [],
    },
    "replicate": {
        "category": "LLM API",
        "label": "Replicate",
        "packages": ["replicate"],
        "imports": ["replicate"],
        "env_keys": ["REPLICATE_API_TOKEN"],
        "urls": ["api.replicate.com"],
        "config_files": [],
    },
    "huggingface": {
        "category": "LLM API",
        "label": "Hugging Face",
        "packages": ["transformers", "huggingface_hub", "diffusers", "datasets", "@huggingface/inference"],
        "imports": ["transformers", "huggingface_hub", "diffusers", "@huggingface/inference"],
        "env_keys": ["HUGGINGFACE_API_KEY", "HF_TOKEN", "HUGGING_FACE_HUB_TOKEN"],
        "urls": ["api-inference.huggingface.co", "huggingface.co"],
        "config_files": [],
    },
    "perplexity": {
        "category": "LLM API",
        "label": "Perplexity AI",
        "packages": [],
        "imports": [],
        "env_keys": ["PERPLEXITY_API_KEY"],
        "urls": ["api.perplexity.ai"],
        "config_files": [],
    },
    "ollama": {
        "category": "LLM API",
        "label": "Ollama (local)",
        "packages": ["ollama"],
        "imports": ["ollama"],
        "env_keys": ["OLLAMA_BASE_URL", "OLLAMA_HOST"],
        "urls": ["localhost:11434", "ollama.ai"],
        "config_files": [],
    },

    # ── AI Frameworks / Orchestration ─────────────────────────────────────────
    "langchain": {
        "category": "Framework",
        "label": "LangChain",
        "packages": ["langchain", "langchain-core", "langchain-community", "langchain-openai", "langchain-anthropic", "@langchain/core", "@langchain/openai"],
        "imports": ["langchain", "from langchain", "@langchain/"],
        "env_keys": ["LANGCHAIN_API_KEY", "LANGCHAIN_TRACING_V2", "LANGSMITH_API_KEY"],
        "urls": ["api.smith.langchain.com", "smith.langchain.com"],
        "config_files": [],
    },
    "llamaindex": {
        "category": "Framework",
        "label": "LlamaIndex",
        "packages": ["llama-index", "llama_index", "llamaindex", "@llamaindex/core"],
        "imports": ["llama_index", "llamaindex", "@llamaindex/"],
        "env_keys": ["LLAMA_CLOUD_API_KEY"],
        "urls": ["api.llamaindex.ai"],
        "config_files": [],
    },
    "dspy": {
        "category": "Framework",
        "label": "DSPy",
        "packages": ["dspy-ai", "dspy"],
        "imports": ["dspy", "import dspy"],
        "env_keys": [],
        "urls": [],
        "config_files": [],
    },
    "crewai": {
        "category": "Framework",
        "label": "CrewAI",
        "packages": ["crewai", "crewai-tools"],
        "imports": ["crewai", "from crewai"],
        "env_keys": [],
        "urls": ["api.crewai.com"],
        "config_files": [],
    },
    "autogen": {
        "category": "Framework",
        "label": "AutoGen / AG2",
        "packages": ["pyautogen", "autogen-agentchat", "ag2"],
        "imports": ["autogen", "from autogen"],
        "env_keys": [],
        "urls": [],
        "config_files": [],
    },
    "semantic_kernel": {
        "category": "Framework",
        "label": "Semantic Kernel",
        "packages": ["semantic-kernel"],
        "imports": ["semantic_kernel", "semantic-kernel"],
        "env_keys": [],
        "urls": [],
        "config_files": [],
    },
    "haystack": {
        "category": "Framework",
        "label": "Haystack",
        "packages": ["haystack-ai", "farm-haystack"],
        "imports": ["haystack"],
        "env_keys": ["HAYSTACK_TELEMETRY_ENABLED"],
        "urls": [],
        "config_files": [],
    },
    "pydantic_ai": {
        "category": "Framework",
        "label": "Pydantic AI",
        "packages": ["pydantic-ai"],
        "imports": ["pydantic_ai"],
        "env_keys": [],
        "urls": [],
        "config_files": [],
    },
    "instructor": {
        "category": "Framework",
        "label": "Instructor",
        "packages": ["instructor"],
        "imports": ["instructor"],
        "env_keys": [],
        "urls": [],
        "config_files": [],
    },

    # ── Vector Databases ───────────────────────────────────────────────────────
    "pinecone": {
        "category": "Vector DB",
        "label": "Pinecone",
        "packages": ["pinecone-client", "pinecone"],
        "imports": ["pinecone"],
        "env_keys": ["PINECONE_API_KEY", "PINECONE_ENVIRONMENT"],
        "urls": ["api.pinecone.io", "controller.pinecone.io"],
        "config_files": [],
    },
    "weaviate": {
        "category": "Vector DB",
        "label": "Weaviate",
        "packages": ["weaviate-client"],
        "imports": ["weaviate"],
        "env_keys": ["WEAVIATE_API_KEY", "WEAVIATE_URL"],
        "urls": ["weaviate.io"],
        "config_files": [],
    },
    "chroma": {
        "category": "Vector DB",
        "label": "Chroma",
        "packages": ["chromadb"],
        "imports": ["chromadb"],
        "env_keys": ["CHROMA_API_KEY", "CHROMA_HOST"],
        "urls": ["api.trychroma.com"],
        "config_files": [],
    },
    "qdrant": {
        "category": "Vector DB",
        "label": "Qdrant",
        "packages": ["qdrant-client"],
        "imports": ["qdrant_client"],
        "env_keys": ["QDRANT_API_KEY", "QDRANT_URL"],
        "urls": ["qdrant.io", "cloud.qdrant.io"],
        "config_files": [],
    },
    "milvus": {
        "category": "Vector DB",
        "label": "Milvus / Zilliz",
        "packages": ["pymilvus"],
        "imports": ["pymilvus"],
        "env_keys": ["MILVUS_API_KEY", "ZILLIZ_API_KEY"],
        "urls": ["zillizcloud.com"],
        "config_files": [],
    },

    # ── AI Dev Tools (IDE / Coding) ────────────────────────────────────────────
    "github_copilot": {
        "category": "Dev Tool",
        "label": "GitHub Copilot",
        "packages": [],
        "imports": [],
        "env_keys": ["GITHUB_COPILOT_TOKEN"],
        "urls": ["copilot-proxy.githubusercontent.com"],
        "config_files": [".github/copilot-instructions.md", ".copilot/"],
    },
    "cursor": {
        "category": "Dev Tool",
        "label": "Cursor",
        "packages": [],
        "imports": [],
        "env_keys": [],
        "urls": [],
        "config_files": [".cursorrules", ".cursor/"],
    },
    "continue": {
        "category": "Dev Tool",
        "label": "Continue.dev",
        "packages": [],
        "imports": [],
        "env_keys": [],
        "urls": [],
        "config_files": [".continue/", ".continuerc.json"],
    },
    "codeium": {
        "category": "Dev Tool",
        "label": "Codeium / Windsurf",
        "packages": [],
        "imports": [],
        "env_keys": ["CODEIUM_API_KEY"],
        "urls": ["codeium.com"],
        "config_files": [".codeiumignore"],
    },
    "tabnine": {
        "category": "Dev Tool",
        "label": "Tabnine",
        "packages": [],
        "imports": [],
        "env_keys": [],
        "urls": ["tabnine.com"],
        "config_files": [".tabnine/"],
    },

    # ── Observability / LLMOps ────────────────────────────────────────────────
    "langsmith": {
        "category": "Observability",
        "label": "LangSmith",
        "packages": ["langsmith"],
        "imports": ["langsmith"],
        "env_keys": ["LANGSMITH_API_KEY", "LANGCHAIN_TRACING_V2"],
        "urls": ["smith.langchain.com"],
        "config_files": [],
    },
    "helicone": {
        "category": "Observability",
        "label": "Helicone",
        "packages": ["helicone"],
        "imports": ["helicone"],
        "env_keys": ["HELICONE_API_KEY"],
        "urls": ["oai.helicone.ai", "anthropic.helicone.ai"],
        "config_files": [],
    },
    "braintrust": {
        "category": "Observability",
        "label": "Braintrust",
        "packages": ["braintrust"],
        "imports": ["braintrust"],
        "env_keys": ["BRAINTRUST_API_KEY"],
        "urls": ["braintrustdata.com"],
        "config_files": [],
    },
    "arize": {
        "category": "Observability",
        "label": "Arize / Phoenix",
        "packages": ["arize", "arize-phoenix", "opentelemetry-sdk"],
        "imports": ["arize", "phoenix"],
        "env_keys": ["ARIZE_API_KEY", "ARIZE_SPACE_KEY"],
        "urls": ["api.arize.com"],
        "config_files": [],
    },
    "weights_biases": {
        "category": "Observability",
        "label": "Weights & Biases",
        "packages": ["wandb"],
        "imports": ["wandb"],
        "env_keys": ["WANDB_API_KEY"],
        "urls": ["api.wandb.ai"],
        "config_files": [],
    },

    # ── No-code / Workflow Builders ───────────────────────────────────────────
    "flowise": {
        "category": "No-code",
        "label": "Flowise",
        "packages": ["flowise"],
        "imports": [],
        "env_keys": ["FLOWISE_SECRETKEY_OVERWRITE"],
        "urls": [],
        "config_files": ["flowise.json", ".flowise/"],
    },
    "n8n": {
        "category": "No-code",
        "label": "n8n",
        "packages": ["n8n"],
        "imports": [],
        "env_keys": ["N8N_ENCRYPTION_KEY"],
        "urls": ["api.n8n.io"],
        "config_files": [".n8n/"],
    },
}
